### ISSUE TITLE
Negative numbers when left open

### ISSUE THREAD

**Issue by ts-web** [alexburner/daylight.website#5]
Hi there, great site, I keep it open all the time.

Sometimes when I open it in the morning, say at 10am, it shows a negative number like "-2h 55m until sunrise". The visuals are otherwise accurate. Then when I refresh the page, it shows the correct text: "9h 20m until sunset".

**Comment by alexburner** [comment]
Hey I'm glad you're enjoying it! And that is super weird, I'll start a long-running version & try to repo the issue

**Comment by alexburner** [comment]
Thank you! That is helpful. I've also reproduced the problem locally, still not sure the root cause

**Comment by alexburner** [comment]
Got it! SunCalc was misinterpreting the time stamp when the day ticked over at midnight, and calculating times for the previous day. Setting the time to noon before passing it seems to fix the issue: https://github.com/alexburner/daylight.website/commit/2be7781ab37ce08aafa8fc695cba42ba5edace4c

This should fix the negative numbers

**Comment by alexburner** [comment]
I also added a PR with a test showing the problem in the underlying library: https://github.com/mourner/suncalc/pull/123
